version: "2"

checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 50

plugins:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - REFACTOR
  editorconfig:
    enabled: true

exclude_patterns:
  - "ProjectSettings/"
  - "Packages/"
  - "Assets/Httx/Tests/**/*.cs"
  - "Assets/Httx/Runtime/Externals/**/*.cs"
  - "**/*.unity"
  - "**/*.meta"
  - "**/*.asmdef"
